apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_HOST: mssql-service
  DB_PORT: "1433"
  DB_NAME: mydb
  DB_USER: sa
  DB_PASSWORD: StrongPassword123!

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
        - name: java-api
          image: seu-registro/java-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config

---
apiVersion: v1
kind: Service
metadata:
  name: java-api-service
spec:
  selector:
    app: java-api
  ports:
    - protocol: HTTP
      port: 80
      targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: java-api-route
spec:
  to:
    kind: Service
    name: java-api-service
  port:
    targetPort: 80
  tls:
    termination: edge

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
